[package]
name = "ore-app"
version = "1.1.0"
description = "Ore is a digital currency everyone can mine. Mine at home or on your phone."
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply"
documentation = "https://ore.supply"
repository = "https://github.com/hardhatchad/ore-app"
readme = "./README.md"
keywords = ["solana", "crypto", "mining"]

[features]
default = ["web"]
bundle = []
web = [
    "gloo",
    "gloo-storage",
    "js-sys",
    "serde-wasm-bindgen",
    "solana-client-wasm",
    "solana-extra-wasm",
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "wasm-logger",
    "web-sys",
    "web-time",
]

[dependencies]
async-std = "1.12.0"
bincode = "1.3.3"
cached = "0.47.0"
chrono = "0.4.34"
dioxus = { version = "0.5", features = ["web", "router"] }
dioxus-std = { version = "0.5", features = ["clipboard", "utils"] }
drillx = { version = "0.2.0", path = "../drillx/drillx" }
futures = "0.3.30"
futures-util = "0.3.30"
gloo = { version = "0.11.0", optional = true }
gloo-storage = { version = "0.3.0", optional = true }
is-url = { version = "1.0.4" }
js-sys = { version = "0.3.67", optional = true }
log = "0.4.20"
ore = { package = "ore-program", path = "../ore", features = ["no-entrypoint"] }
ore-types = { path = "../ore-infra/types" }
# ore-types = "0.0.5"
qrcode-generator = "4.1.9"
rand = "0.8.5"
reqwest = "0.11.24"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = { version = "0.6.3", optional = true }
serde_json = "1.0"
solana-client-wasm = { version = "1.18", optional = true }
solana-extra-wasm = { version = "1.18", optional = true }
url = "2.5.0"
wasm-bindgen = { version = "0.2.91", optional = true }
wasm-bindgen-futures = { version = "0.4.41", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
web-time = { version = "1.0.0", optional = true }

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
    'console',
    'Clipboard',
    'Document',
    'HtmlElement',
    'HtmlInputElement',
    "IdbFactory", 
    "IdbDatabase", 
    "IdbObjectStore", 
    "IdbTransaction",
    'MessageEvent',
    'Navigator',
    'Window',
    'Worker',
    'WorkerOptions',
    'WorkerType',
    'WorkerGlobalScope',
]

[patch.crates-io]
solana-client-wasm = { version = "1.18", path = "../solana-playground/wasm/solana-client" }
solana-extra-wasm = { version = "1.18", path = "../solana-playground/wasm/utils/solana-extra" }
